# Generated by Django 5.1.5 on 2025-01-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0002_item_created_by_item_updated_by_project_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_priorities', to='organiser.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_item_priority_name_per_project'), models.UniqueConstraint(fields=('project', 'order'), name='unique_item_priority_order_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kanban_column_order', models.PositiveSmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_statuses', to='organiser.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_item_status_name_per_project'), models.UniqueConstraint(fields=('project', 'kanban_column_order'), name='unique_item_status_kanban_column_order_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('nestable', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_types', to='organiser.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_item_type_name_per_project'), models.UniqueConstraint(fields=('project', 'order'), name='unique_item_type_order_per_project')],
            },
        ),
    ]
