# Generated by Django 5.1.5 on 2025-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0003_itempriority_itemstatus_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstatus',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='itemstatus',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='unique_item_status_order_per_project'),
        ),
    ]
