# Generated by Django 5.1.5 on 2025-01-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0004_itemstatus_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organiser.itempriority'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser.itemstatus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser.itemtype'),
        ),
    ]
