# Generated by Django 5.1.5 on 2025-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0005_item_item_priority_alter_item_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempriority',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemstatus',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='itempriority',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('project',), name='only_one_item_priority_default_per_project'),
        ),
        migrations.AddConstraint(
            model_name='itemstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('project',), name='only_one_item_status_default_per_project'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('project',), name='only_one_item_type_default_per_project'),
        ),
    ]
