# Generated by Django 5.1.5 on 2025-01-16 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0006_itempriority_default_itemstatus_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempriority',
            options={'default_related_name': 'item_priorities'},
        ),
        migrations.AlterModelOptions(
            name='itemstatus',
            options={'default_related_name': 'item_statuses'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'default_related_name': 'item_types'},
        ),
        migrations.RemoveConstraint(
            model_name='itempriority',
            name='unique_item_priority_name_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itempriority',
            name='unique_item_priority_order_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itempriority',
            name='only_one_item_priority_default_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itemstatus',
            name='unique_item_status_name_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itemstatus',
            name='unique_item_status_order_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itemstatus',
            name='only_one_item_status_default_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itemtype',
            name='unique_item_type_name_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itemtype',
            name='unique_item_type_order_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='itemtype',
            name='only_one_item_type_default_per_project',
        ),
        migrations.AddField(
            model_name='item',
            name='changelog',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='kanban_row_order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='outcome',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organiser.itempriority'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organiser.itemstatus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='organiser.itemtype'),
        ),
        migrations.AlterField(
            model_name='itempriority',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser.project'),
        ),
        migrations.AlterField(
            model_name='itemstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser.project'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser.project'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('project', 'parent', 'kanban_row_order'), name='unique_item_kanban_row_order_per_parent_and_project'),
        ),
    ]
