# Generated by Django 5.1.5 on 2025-01-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0007_alter_itempriority_options_alter_itemstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kanban_row_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
