# Generated by Django 5.1.5 on 2025-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0008_alter_item_kanban_row_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemstatus',
            name='unique_item_status_kanban_column_order_per_project',
        ),
        migrations.RemoveField(
            model_name='itemstatus',
            name='kanban_column_order',
        ),
        migrations.AlterField(
            model_name='item',
            name='changelog',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
