# Generated by Django 5.1.5 on 2025-01-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0009_remove_itemstatus_unique_item_status_kanban_column_order_per_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemPriority',
            new_name='ItemPriorityOption',
        ),
        migrations.RenameModel(
            old_name='ItemStatus',
            new_name='ItemStatusOption',
        ),
        migrations.RenameModel(
            old_name='ItemType',
            new_name='ItemTypeOption',
        ),
    ]
