# Generated by Django 5.1.5 on 2025-01-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0010_rename_itempriority_itempriorityoption_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_kanban_row_order_per_parent_and_project',
        ),
    ]
